name: Node CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '10'

      - run: |
          yarn
          yarn test
          yarn dist
          wget -q -O - https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.1/node-v57-win32-x64.tar.gz | tar zxf -
          wget -q -O - https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.1/node-v57-linux-x64.tar.gz | tar zxf -
          wget -q -O - https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.1/node-v57-darwin-x64.tar.gz | tar zxf -
          mkdir -p foxgis-server-lite-win foxgis-server-lite-linux foxgis-server-lite-macos
          mv dist/foxgis-server-lite-win.exe node-v64-win32-x64/node_sqlite3.node foxgis-server-lite-win/
          mv dist/foxgis-server-lite-linux node-v64-linux-x64/node_sqlite3.node foxgis-server-lite-linux/
          mv dist/foxgis-server-lite-macos node-v64-darwin-x64/node_sqlite3.node foxgis-server-lite-macos/
          cp -R data foxgis-server-lite-win/
          cp -R data foxgis-server-lite-linux/
          cp -R data foxgis-server-lite-macos/
          tar zcf foxgis-server-lite-win.tar.gz foxgis-server-lite-win
          tar zcf foxgis-server-lite-linux.tar.gz foxgis-server-lite-linux
          tar zcf foxgis-server-lite-macos.tar.gz foxgis-server-lite-macos
          mv foxgis-server-lite-win.tar.gz foxgis-server-lite-linux.tar.gz foxgis-server-lite-macos.tar.gz docs/

      - uses: JamesIves/github-pages-deploy-action@3.5.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: docs
